version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - local
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  # APP*****************************************
  spring_mongodb:
    image: starterpack/spring-boot-mongodb:latest
    environment:
      - MONGODB_DB_NAME=addressbook
    networks:
      - local
    container_name: spring_mongodb
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - mongodb
    links:
      - mongodb
volumes:
  db-data:
networks:
  local:
    driver: bridge